// Package apiaccount provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apiaccount

import (
	"time"
)

// Defines values for OnboardingStatus.
const (
	OnboardingStatusCompleted  OnboardingStatus = "completed"
	OnboardingStatusFactionSet OnboardingStatus = "faction_set"
	OnboardingStatusNameSet    OnboardingStatus = "name_set"
	OnboardingStatusNotStarted OnboardingStatus = "not_started"
)

// Valid indicates whether the value is a known member of the OnboardingStatus enum.
func (e OnboardingStatus) Valid() bool {
	switch e {
	case OnboardingStatusCompleted:
		return true
	case OnboardingStatusFactionSet:
		return true
	case OnboardingStatusNameSet:
		return true
	case OnboardingStatusNotStarted:
		return true
	default:
		return false
	}
}

// AddExpRequest defines model for AddExpRequest.
type AddExpRequest struct {
	ExpGain int64 `json:"exp_gain"`
}

// AwardGameExpRequest defines model for AwardGameExpRequest.
type AwardGameExpRequest struct {
	MatchType string `json:"match_type"`
	Player1ID string `json:"player1_id"`
	Player2ID string `json:"player2_id"`
	Reason    string `json:"reason"`
	WinnerNum int64  `json:"winner_num"`
}

// BattleLimitResponse defines model for BattleLimitResponse.
type BattleLimitResponse struct {
	CanBattle        bool  `json:"can_battle"`
	DailyBattleCount int64 `json:"daily_battle_count"`
	DailyBattleLimit int64 `json:"daily_battle_limit"`
}

// FactionGrantRequest defines model for FactionGrantRequest.
type FactionGrantRequest struct {
	Faction string `json:"faction"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// ListFactionsResponse defines model for ListFactionsResponse.
type ListFactionsResponse struct {
	Factions []string `json:"factions"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	FirebaseUID string `json:"firebase_uid"`
}

// OnboardingStatus オンボーディング進捗。`internal/domain/onboarding_status.go` の定数群と完全一致。
// drift は enum_drift_test.go で検知する。
type OnboardingStatus string

// PlayerResponse PlayerView + computed level progress を JSON 化した、内部 REST 契約の唯一の
// Player 表現。GET /players/{playerId} とその親戚 endpoint が共通で返す。
type PlayerResponse struct {
	CreatedAt      time.Time `json:"created_at"`
	EquippedIconNo *int64    `json:"equipped_icon_no,omitempty"`
	Exp            int64     `json:"exp"`
	FirebaseUID    string    `json:"firebase_uid"`

	// InitialFaction オンボーディングで選択した faction (player_factions.is_initial=TRUE から導出)。
	InitialFaction   *string `json:"initial_faction,omitempty"`
	IsPremium        bool    `json:"is_premium"`
	Level            int64   `json:"level"`
	LevelExpCurrent  int64   `json:"level_exp_current"`
	LevelExpRequired int64   `json:"level_exp_required"`

	// Name オンボーディング未完了時は省略 (omit) される。
	Name *string `json:"name,omitempty"`

	// OnboardingStatus オンボーディング進捗。`internal/domain/onboarding_status.go` の定数群と完全一致。
	// drift は enum_drift_test.go で検知する。
	OnboardingStatus OnboardingStatus `json:"onboarding_status"`
	PlayerID         string           `json:"player_id"`
	PremiumExpiresAt *time.Time       `json:"premium_expires_at,omitempty"`
	UpdatedAt        time.Time        `json:"updated_at"`
}

// PlayerSettingsResponse defines model for PlayerSettingsResponse.
type PlayerSettingsResponse struct {
	BgmVolume   int64     `json:"bgm_volume"`
	Language    string    `json:"language"`
	PlayerID    string    `json:"player_id"`
	PushEnabled bool      `json:"push_enabled"`
	SeVolume    int64     `json:"se_volume"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	FirebaseUID string `json:"firebase_uid"`
}

// SelectInitialFactionRequest Scenario calls this once the tutorial/story pins the player's faction choice;
// account UPSERTs player_factions with is_initial=TRUE in one tx.
type SelectInitialFactionRequest struct {
	FactionID string `json:"faction_id"`
}

// UpdateNameRequest defines model for UpdateNameRequest.
type UpdateNameRequest struct {
	Name string `json:"name"`
}

// UpdatePremiumRequest ExpiresAtMillis は UNIX ミリ秒タイムスタンプ。null は NULL リセット。
type UpdatePremiumRequest struct {
	ExpiresAtMillis *int64 `json:"expires_at_millis,omitempty"`
	IsPremium       bool   `json:"is_premium"`
}

// UpdateSettingsRequest Partial update: nil フィールドは現状維持 (COALESCE in SQL)。
// 最低 1 つは non-nil である必要がある (handler 層で検証)。
type UpdateSettingsRequest struct {
	BgmVolume   *int64  `json:"bgm_volume,omitempty"`
	Language    *string `json:"language,omitempty"`
	PushEnabled *bool   `json:"push_enabled,omitempty"`
	SeVolume    *int64  `json:"se_volume,omitempty"`
}

// ValidateNameForOnboardingRequest オンボード内 name 入力ステップで scenario が呼ぶ表示名バリデーション専用 DTO。
// 値は永続化されない。書き込みは onboarding-name-set subscriber 経由。
type ValidateNameForOnboardingRequest struct {
	Name string `json:"name"`
}

// PlayerID defines model for PlayerIdPath.
type PlayerID = string

// LoginPlayerJSONRequestBody defines body for LoginPlayer for application/json ContentType.
type LoginPlayerJSONRequestBody = LoginRequest

// RegisterPlayerJSONRequestBody defines body for RegisterPlayer for application/json ContentType.
type RegisterPlayerJSONRequestBody = RegisterRequest

// AwardGameExpJSONRequestBody defines body for AwardGameExp for application/json ContentType.
type AwardGameExpJSONRequestBody = AwardGameExpRequest

// AddExpJSONRequestBody defines body for AddExp for application/json ContentType.
type AddExpJSONRequestBody = AddExpRequest

// GrantFactionJSONRequestBody defines body for GrantFaction for application/json ContentType.
type GrantFactionJSONRequestBody = FactionGrantRequest

// SelectInitialFactionJSONRequestBody defines body for SelectInitialFaction for application/json ContentType.
type SelectInitialFactionJSONRequestBody = SelectInitialFactionRequest

// UpdateNameJSONRequestBody defines body for UpdateName for application/json ContentType.
type UpdateNameJSONRequestBody = UpdateNameRequest

// ValidateNameForOnboardingJSONRequestBody defines body for ValidateNameForOnboarding for application/json ContentType.
type ValidateNameForOnboardingJSONRequestBody = ValidateNameForOnboardingRequest

// UpdatePremiumJSONRequestBody defines body for UpdatePremium for application/json ContentType.
type UpdatePremiumJSONRequestBody = UpdatePremiumRequest

// UpdatePlayerSettingsJSONRequestBody defines body for UpdatePlayerSettings for application/json ContentType.
type UpdatePlayerSettingsJSONRequestBody = UpdateSettingsRequest
