// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apiaccount

import (
	"time"
)

// PlayerResponse is returned by GET /internal/v1/players/:playerId and kin. PlayerView + computed level progress を JSON 化した、内部 REST 契約の唯一の Player 表現。
type PlayerResponse struct {
	PlayerID         string     `json:"player_id"`
	FirebaseUID      string     `json:"firebase_uid"`
	Name             *string    `json:"name,omitempty"`
	Level            int64      `json:"level"`
	Exp              int64      `json:"exp"`
	IsPremium        bool       `json:"is_premium"`
	EquippedIconNo   *int64     `json:"equipped_icon_no,omitempty"`
	InitialFaction   *string    `json:"initial_faction,omitempty"`
	OnboardingStatus string     `json:"onboarding_status"`
	PremiumExpiresAt *time.Time `json:"premium_expires_at,omitempty"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	LevelExpCurrent  int64      `json:"level_exp_current"`
	LevelExpRequired int64      `json:"level_exp_required"`
}

// PlayerSettingsResponse is returned by GET / PUT /internal/v1/players/:playerId/settings.
type PlayerSettingsResponse struct {
	PlayerID    string    `json:"player_id"`
	Language    string    `json:"language"`
	BgmVolume   int64     `json:"bgm_volume"`
	SeVolume    int64     `json:"se_volume"`
	PushEnabled bool      `json:"push_enabled"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// BattleLimitResponse is returned by GET /internal/v1/players/:playerId/battle-limit.
type BattleLimitResponse struct {
	DailyBattleCount int64 `json:"daily_battle_count"`
	DailyBattleLimit int64 `json:"daily_battle_limit"`
	CanBattle        bool  `json:"can_battle"`
}

// ListFactionsResponse is returned by GET /internal/v1/players/:playerId/factions.
type ListFactionsResponse struct {
	Factions []string `json:"factions"`
}

// RegisterRequest is the body for POST /internal/v1/auth/register. firebase_uid のみで登録する。表示名はオンボード内 name 入力ステップで PUT /internal/v1/players/:playerId/name 経由で確定するため、Register 時には受け取らない。
type RegisterRequest struct {
	FirebaseUID string `json:"firebase_uid"`
}

// LoginRequest is the body for POST /internal/v1/auth/login.
type LoginRequest struct {
	FirebaseUID string `json:"firebase_uid"`
}

// UpdateNameRequest is the body for PUT /internal/v1/players/:playerId/name.
type UpdateNameRequest struct {
	Name string `json:"name"`
}

// ValidateNameForOnboardingRequest is the body for POST /internal/v1/players/:playerId/onboarding/name/validate. Validation only; the value is not persisted. Scenario calls this before publishing onboarding-name-set so that 4xx can be relayed to the user synchronously.
type ValidateNameForOnboardingRequest struct {
	Name string `json:"name"`
}

// UpdatePremiumRequest is the body for PUT /internal/v1/players/:playerId/premium. ExpiresAtMillis is a UNIX millisecond timestamp; null resets to NULL.
type UpdatePremiumRequest struct {
	IsPremium       bool   `json:"is_premium"`
	ExpiresAtMillis *int64 `json:"expires_at_millis,omitempty"`
}

// AddExpRequest is the body for POST /internal/v1/players/:playerId/exp.
type AddExpRequest struct {
	ExpGain int64 `json:"exp_gain"`
}

// AwardGameExpRequest is the body for POST /internal/v1/players/award-game-exp.
type AwardGameExpRequest struct {
	Player1ID string `json:"player1_id"`
	Player2ID string `json:"player2_id"`
	WinnerNum int64  `json:"winner_num"`
	Reason    string `json:"reason"`
	MatchType string `json:"match_type"`
}

// FactionGrantRequest is the body for POST /internal/v1/players/:playerId/factions.
type FactionGrantRequest struct {
	Faction string `json:"faction"`
}

// SelectInitialFactionRequest is the body for POST /internal/v1/players/:playerId/factions/select. Scenario calls this once the tutorial/story pins the player's faction choice; account UPSERTs player_factions with is_initial=TRUE in one tx. Card distribution is triggered separately via the player-onboarded Pub/Sub event consumed by card service (ADR-026 / ADR-032: REST grant pathway is removed).
type SelectInitialFactionRequest struct {
	FactionID string `json:"faction_id"`
}

// UpdateSettingsRequest is the body for PUT /internal/v1/players/:playerId/settings. Partial update semantics: nil fields are left unchanged (COALESCE in SQL). At least one non-nil field is required.
type UpdateSettingsRequest struct {
	Language    *string `json:"language,omitempty"`
	BgmVolume   *int64  `json:"bgm_volume,omitempty"`
	SeVolume    *int64  `json:"se_volume,omitempty"`
	PushEnabled *bool   `json:"push_enabled,omitempty"`
}

