/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サービス死活監視 (ClusterIP 内部のみ) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新規プレイヤーを登録する (gateway が Firebase UID を中継)
         * @description 表示名はオンボード内 name 入力ステップで PUT /api/v1/account/me/name 経由で確定するため、
         *     Register 時には受け取らない。
         */
        post: operations["registerPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Firebase UID でログインしてプレイヤー情報を返す */
        post: operations["loginPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/auth/by-firebase-uid/{firebaseUID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Firebase UID からプレイヤーを検索する (gateway などサービス間ルックアップ用) */
        get: operations["getPlayerByFirebaseUID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/players/{playerID}/factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定プレイヤーの所持ファクション一覧を返す (card → account)
         * @description card がデッキ作成/編集時に宣言ファクションの所持を検証するためのサービス間ルックアップ。
         *     player_id を path で受けるため bootstrap 系と同様に認証なし (/internal 配下)。
         */
        get: operations["listPlayerFactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/players/award-game-exp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 対戦終了後に両プレイヤーへ経験値を付与する (battle → account)
         * @description body に両 player_id を含むサーバー間バッチ呼び出し。JWT sub では表現できないため
         *     bootstrap 系と同様に認証なし (/internal 配下)。
         */
        post: operations["awardGameExp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/players/revert-battle-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止で無効になった対戦の消費バトル回数を両プレイヤーに戻す (gateway → account)
         * @description body に両 player_id・対戦識別子・バトル回数を消費した時刻を含むサーバー間バッチ呼び出し。
         *     JWT sub では表現できないため bootstrap 系と同様に認証なし (/internal 配下)。
         *     同一 game_id の呼び出しは 1 回のみ適用され、以降は idempotent に 204 を返す。
         */
        post: operations["revertBattleCount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認証済みプレイヤーの情報を返す (レベル進捗を含む) */
        get: operations["getPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** プレイヤー名を変更する */
        put: operations["updateName"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/onboarding/name/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * オンボード内 name 入力ステップで scenario が呼ぶ表示名バリデーション (書き込みなし)
         * @description バリデーション SSoT は account の internal/domain/name.go。
         *     書き込みは onboarding-name-set subscriber が行う。
         */
        post: operations["validateNameForOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/battle-limit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 1 日のバトル回数制限と残り回数を返す */
        get: operations["getBattleLimit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/battle-limit/increment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** バトル回数を 1 増やす (バトル開始時に gateway が呼び出す) */
        post: operations["incrementBattleCount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/premium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** プレミアムステータスを更新する (shop webhook 経由) */
        put: operations["updatePremium"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/exp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 経験値を加算する */
        post: operations["addExp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プレイヤーが所有するファクション一覧を返す */
        get: operations["listFactions"];
        put?: never;
        /** ファクション所有権を付与する (購入・報酬等) */
        post: operations["grantFaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/factions/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 初期ファクション選択 (チュートリアル完了時に scenario が呼び出す)
         * @description 冪等。既に選択済みの場合は 409 を返すがクライアントにとってはエラーではない。
         */
        post: operations["selectInitialFaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プレイヤー設定を返す */
        get: operations["getPlayerSettings"];
        /**
         * プレイヤー設定を部分更新する
         * @description Partial update semantics: nil フィールドは現状維持 (COALESCE in SQL)。
         *     全 nil リクエストは 400 で弾く。
         */
        put: operations["updatePlayerSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        /**
         * @description PlayerView + computed level progress を JSON 化した、内部 REST 契約の唯一の
         *     Player 表現。GET /api/v1/account/me とその親戚 endpoint が共通で返す。
         */
        PlayerResponse: {
            player_id: string;
            firebase_uid: string;
            /** @description オンボーディング未完了時は省略 (omit) される。 */
            name?: string;
            /** Format: int64 */
            level: number;
            /** Format: int64 */
            exp: number;
            is_premium: boolean;
            /** Format: int64 */
            equipped_icon_no?: number;
            /** @description オンボーディングで選択した faction (player_factions.is_initial=TRUE から導出)。 */
            initial_faction?: string;
            onboarding_status: components["schemas"]["OnboardingStatus"];
            /** Format: date-time */
            premium_expires_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            level_exp_current: number;
            /** Format: int64 */
            level_exp_required: number;
        };
        PlayerSettingsResponse: {
            player_id: string;
            language: string;
            /** Format: int64 */
            bgm_volume: number;
            /** Format: int64 */
            se_volume: number;
            push_enabled: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        BattleLimitResponse: {
            /** Format: int64 */
            daily_battle_count: number;
            /** Format: int64 */
            daily_battle_limit: number;
            can_battle: boolean;
        };
        FactionListing: {
            factions: string[];
        };
        RegisterRequest: {
            firebase_uid: string;
        };
        LoginRequest: {
            firebase_uid: string;
        };
        UpdateNameRequest: {
            name: string;
        };
        /**
         * @description オンボード内 name 入力ステップで scenario が呼ぶ表示名バリデーション専用 DTO。
         *     値は永続化されない。書き込みは onboarding-name-set subscriber 経由。
         */
        ValidateNameForOnboardingRequest: {
            name: string;
        };
        /** @description ExpiresAtMillis は UNIX ミリ秒タイムスタンプ。null は NULL リセット。 */
        UpdatePremiumRequest: {
            is_premium: boolean;
            /** Format: int64 */
            expires_at_millis?: number;
        };
        AddExpRequest: {
            /** Format: int64 */
            exp_gain: number;
        };
        AwardGameExpRequest: {
            player1_id: string;
            player2_id: string;
            /** Format: int64 */
            winner_num: number;
            reason: string;
            match_type: string;
        };
        /**
         * @description consumed_at_millis はバトル回数を消費した (gateway が increment を呼んだ) 時刻の
         *     UNIX ミリ秒。停止発生時刻ではなく、消費時点の時刻を渡す。ゲーム日境界 (JST 05:00)
         *     の判定はこの時刻を基準に account 側で行う。0 以下は 400 になる。
         */
        RevertBattleCountRequest: {
            game_id: string;
            player1_id: string;
            player2_id: string;
            /** Format: int64 */
            consumed_at_millis: number;
        };
        FactionGrantRequest: {
            faction: string;
        };
        /**
         * @description Scenario calls this once the tutorial/story pins the player's faction choice;
         *     account UPSERTs player_factions with is_initial=TRUE in one tx.
         */
        SelectInitialFactionRequest: {
            faction_id: string;
        };
        /**
         * @description Partial update: nil フィールドは現状維持 (COALESCE in SQL)。
         *     最低 1 つは non-nil である必要がある (handler 層で検証)。
         */
        UpdateSettingsRequest: {
            language?: string;
            /** Format: int64 */
            bgm_volume?: number;
            /** Format: int64 */
            se_volume?: number;
            push_enabled?: boolean;
        };
        /**
         * @description オンボーディング進捗。`internal/domain/onboarding_status.go` の定数群と完全一致。
         *     drift は enum_drift_test.go で検知する。
         * @enum {string}
         */
        OnboardingStatus: "not_started" | "name_set" | "faction_set" | "completed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    registerPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description firebase_uid が空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 同一 firebase_uid で既に登録済み */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description firebase_uid が空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlayerByFirebaseUID: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                firebaseUID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プレイヤー情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description firebaseUID が空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPlayerFactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playerID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 所持ファクション一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactionListing"];
                };
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    awardGameExp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AwardGameExpRequest"];
            };
        };
        responses: {
            /** @description 付与成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストボディ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revertBattleCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevertBattleCountRequest"];
            };
        };
        responses: {
            /** @description 返却成功 (同一 game_id の再呼び出しも成功扱い) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストボディ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プレイヤー情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNameRequest"];
            };
        };
        responses: {
            /** @description 更新後のプレイヤー情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description name が空 / バリデーション違反 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validateNameForOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateNameForOnboardingRequest"];
            };
        };
        responses: {
            /** @description バリデーション成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description name が空 / 全空白 / 制御文字 / 上限超 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBattleLimit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description バトル制限情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BattleLimitResponse"];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    incrementBattleCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description インクリメント成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePremium: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePremiumRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストボディ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addExp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddExpRequest"];
            };
        };
        responses: {
            /** @description 加算成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストボディ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ファクション一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactionListing"];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    grantFaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactionGrantRequest"];
            };
        };
        responses: {
            /** @description 付与成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description faction が空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    selectInitialFaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectInitialFactionRequest"];
            };
        };
        responses: {
            /** @description 選択成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description faction_id が空 / 無効なファクション */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 初期ファクション選択済み (冪等 no-op) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlayerSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 設定情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSettingsResponse"];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePlayerSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description 更新後の設定情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSettingsResponse"];
                };
            };
            /** @description language が空 / 全 nil */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
