#!/usr/bin/env python3
"""
Codegen for overload-party-account.

Reads data/models.yaml (SSoT for account-owned types) and emits Go source
files into one of two targets, selected per-section by `target:`:

  target: api   → packages/api-account/*_gen.go (package: apiaccount)
                  内部 REST API の契約 (Request / Response DTO)。json タグのみ付与。
                  Go モジュールとして gateway 等に go-get される。

  target: domain → internal/domain/*_gen.go     (package: domain)
                  純ドメインモデル (Write 集約 + Read Model)。db タグのみ付与し、
                  JSON タグは付けない。リポジトリ層はこの型のみ返す。

「target: both」を許容することで、過渡期に同一型を両方に出すことも可能だが、
本来は型ごとに片方の target に固定するのが望ましい。

Run:  python3 scripts/generate_types.py
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:
    sys.stderr.write("error: PyYAML is required (pip install pyyaml)\n")
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
MODELS_YAML = REPO_ROOT / "data" / "models.yaml"

GENERATED_HEADER = "// Code generated by scripts/generate_types.py; DO NOT EDIT."

# TARGETS は target キーごとの「出力ディレクトリ・package 名・付与するタグ」を保持する。
# emit_tags は YAML フィールドのうちどのタグを Go の struct tag に転写するかを決め、
# これにより同じ型でも target 別に「json のみ」「db のみ」と切り分けられる。
TARGETS = {
    "api": {
        "dir": REPO_ROOT / "packages" / "api-account",
        "package": "apiaccount",
        "emit_tags": ("json",),
    },
    "domain": {
        "dir": REPO_ROOT / "internal" / "domain",
        "package": "domain",
        "emit_tags": ("db",),
    },
}


def _go_type_needs_import(type_str: str) -> set[str]:
    imports: set[str] = set()
    if "time.Time" in type_str or "time." in type_str:
        imports.add("time")
    if "json.RawMessage" in type_str:
        imports.add("encoding/json")
    if "civil.Date" in type_str or "civil." in type_str:
        imports.add("cloud.google.com/go/civil")
    return imports


def _emit_import_block(imports: set[str]) -> list[str]:
    if not imports:
        return []
    std = sorted(i for i in imports if "." not in i.split("/")[0])
    ext = sorted(i for i in imports if "." in i.split("/")[0])
    lines = ["import ("]
    for imp in std:
        lines.append(f'\t"{imp}"')
    if std and ext:
        lines.append("")
    for imp in ext:
        lines.append(f'\t"{imp}"')
    lines.append(")")
    lines.append("")
    return lines


def _emit_type(td: dict, emit_tags: tuple[str, ...]) -> list[str]:
    lines: list[str] = []
    if td.get("comment"):
        lines.append(f"// {td['comment']}")
    lines.append(f"type {td['name']} struct {{")

    fields = td.get("fields", [])
    if fields:
        max_name_len = max(len(f["name"]) for f in fields)
        max_type_len = max(len(str(f["type"])) for f in fields)

    for field in fields:
        fname = field["name"]
        ftype = str(field["type"])
        tags: list[str] = []
        for tag_key in emit_tags:
            if tag_key in field:
                tags.append(f'{tag_key}:"{field[tag_key]}"')
        tag_str = " ".join(tags)

        name_pad = " " * (max_name_len - len(fname) + 1)
        type_pad = " " * (max_type_len - len(ftype) + 1)

        if tag_str:
            line = f"\t{fname}{name_pad}{ftype}{type_pad}`{tag_str}`"
        else:
            line = f"\t{fname}{name_pad}{ftype}"

        if field.get("comment"):
            line += f" // {field['comment']}"
        lines.append(line)

    lines.append("}")
    lines.append("")
    return lines


def _generate_file(file_def: dict, target_key: str) -> None:
    target = TARGETS[target_key]
    package_name = target["package"]
    out_dir = target["dir"]
    emit_tags = target["emit_tags"]

    lines: list[str] = [GENERATED_HEADER, "", f"package {package_name}", ""]

    imports = set(file_def.get("imports", []))
    for td in file_def.get("types", []):
        for field in td.get("fields", []):
            imports |= _go_type_needs_import(str(field["type"]))

    lines.extend(_emit_import_block(imports))

    for td in file_def.get("types", []):
        lines.extend(_emit_type(td, emit_tags))

    out_path = out_dir / f"{file_def['name']}_gen.go"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


def _resolve_targets(target_value: str | None, file_name: str) -> list[str]:
    """`target:` フィールドを正規化して、出力先 target キーの一覧を返す。"""
    if target_value is None:
        sys.stderr.write(
            f"error: file '{file_name}' has no 'target:' field "
            f"(expected one of: api, domain, both)\n"
        )
        sys.exit(1)

    if target_value == "both":
        return ["api", "domain"]
    if target_value in TARGETS:
        return [target_value]

    sys.stderr.write(
        f"error: file '{file_name}' has unknown target '{target_value}' "
        f"(expected one of: api, domain, both)\n"
    )
    sys.exit(1)


def main() -> int:
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    sections = data.get("files")
    if not sections:
        sys.stderr.write("error: data/models.yaml has no `files:` section\n")
        return 1

    for file_def in sections:
        target_keys = _resolve_targets(file_def.get("target"), file_def.get("name", "<unnamed>"))
        for target_key in target_keys:
            _generate_file(file_def, target_key)

    return 0


if __name__ == "__main__":
    sys.exit(main())
